get rid of sudo added klcd.conf to autoload module

diff --git a/code/klcd_final/Makefile b/code/klcd_final/Makefile
--- a/code/klcd_final/Makefile
+++ b/code/klcd_final/Makefile
@@ -5,13 +5,13 @@
 
 ifneq ($(KERNELRELEASE),)
 
-# kbuild part of makefile -----------------------------
+# kbuild part of makefile -------------------------------------------------------------------------
 
 include Kbuild
 
 else
 
-# normal makefile -------------------------------------
+# normal makefile ---------------------------------------------------------------------------------
 
 KDIR ?= /lib/modules/`uname -r`/build
 PWD := `pwd`
@@ -19,7 +19,7 @@ KERNELRELEASE ?= $(shell uname -r)
 TEMP_FILE := $(shell mktemp -u)
 
 #
-# Forward targets to KBuild
+# Forward targets to KBuild (run 'make help' for more information)
 #
 
 default:
@@ -41,29 +41,59 @@ help:
 # Module specific targets
 #
 
-install: modules
+install:
+	@if [ ! -r klcd.ko ]; then \
+	  echo "'klcd.ko' missing. Run 'make' first!" 2>&1; exit 1; \
+	fi
+	@if [ "$(shell id -u)" != "0" ]; then \
+	  echo "You are not root, run this target as root please!" 2>&1; exit 1; \
+	fi
 	@echo "-- copy 'klcd.ko' to '/lib/modules/`uname -r`/extra/' and run depmod --"
-	sudo -E make modules_install 2>&1 | tee $(TEMP_FILE)
+	make modules_install 2>&1 | tee $(TEMP_FILE)
 	@if grep "Warning: modules_install: missing 'System.map' file. Skipping depmod." $(TEMP_FILE); \
 	then \
-	  echo "-- System.map missing. Running depmod manually. --"; \
-	  echo "/sbin/depmod -ae -E /lib/modules/$(KERNELRELEASE)/build/Module.symvers $(KERNELRELEASE)"; \
-	  sudo /sbin/depmod -ae -E /lib/modules/$(KERNELRELEASE)/build/Module.symvers $(KERNELRELEASE); \
+	  echo "-- 'System.map' missing. Running depmod manually using 'Module.symvers'. --"; \
+	  cd /usr/src/linux-headers-`uname -r`; \
+	  /sbin/depmod -ae -E $(KDIR)/Module.symvers $(KERNELRELEASE); \
 	fi
-	@if [ -f $(TEMP_FILE) ]; then sudo rm $(TEMP_FILE); fi 
-	# TODO: copy autorun file for systemd
+	@if [ -f $(TEMP_FILE) ]; then rm $(TEMP_FILE); fi
+	@echo "-- copy 'klcd.conf' to '/etc/modules-load.d/' --"
+	cp klcd.conf /etc/modules-load.d/
+	chmod u+rw,g+r,o+r /etc/modules-load.d/klcd.conf
 
-insmod: install
+uninstall:
+	@if [ "$(shell id -u)" != "0" ]; then \
+	  echo "You are not root, run this target as root please!" 2>&1; exit 1; \
+	fi
+	@echo "-- delete 'klcd.ko' from '/lib/modules/`uname -r`/extra/' --"
+	@if [ -r /lib/modules/`uname -r`/extra/klcd.ko ]; then \
+	  rm /lib/modules/`uname -r`/extra/klcd.ko; \
+	fi
+	@echo "-- Running depmod using 'Module.symvers'. --"
+	@cd /usr/src/linux-headers-`uname -r`; \
+	/sbin/depmod -ae -E $(KDIR)/Module.symvers $(KERNELRELEASE)
+	@echo "-- delete 'klcd.conf' from '/etc/modules-load.d/' --"
+	@if [ -f /etc/modules-load.d/klcd.conf ]; then \
+	  rm /etc/modules-load.d/klcd.conf; \
+	fi
+
+insmod:
+	@if [ "$(shell id -u)" != "0" ]; then \
+	  echo "You are not root, run this target as root please!" 2>&1; exit 1; \
+	fi
 	@echo "-- load module with 'insmod klcd.ko' and change access --"
-	sudo insmod klcd.ko
-	sudo chmod a+w /dev/klcd
+	insmod klcd.ko
+	chmod a+w /dev/klcd
 
-rmmod: install
+rmmod:
+	@if [ "$(shell id -u)" != "0" ]; then \
+	  echo "You are not root, run this target as root please!" 2>&1; exit 1; \
+	fi
 	@echo "-- unload module with 'rmmod klcd.ko' --"
-	sudo rmmod klcd.ko
+	rmmod klcd.ko
 
 .PHONY: clean help install insmod rmmod
 
-# -----------------------------------------------------
+# -------------------------------------------------------------------------------------------------
 
 endif
